name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Install Maven
        run: |
          wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
          tar xzf apache-maven-3.5.4-bin.tar.gz
          ln -s apache-maven-3.5.4 maven
          export PATH=$PATH:$PWD/maven/bin

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
          unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
          export PATH=$PATH:$PWD/sonar-scanner-3.3.0.1492-linux/bin

      - name: Build and Test
        run: mvn test

      - name: SonarQube Scan
        env:
          SONAR_LOGIN: ${{ secrets.LOGIN }}
          SONAR_HOST
