name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Check SonarQube status
        id: sonarqube-status
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/quality/sonarqube_status
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          headers: |
            Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        if: steps.sonarqube-status.outputs.data.status == 'OK'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge branch into master"
          title: "Merge branch into master"
          branch: main
          base: master
